# Generated by Django 4.2 on 2023-05-16 23:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Restaurant_Recommendation_WebSite', '0003_remove_restaurant_image_restaurant_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='users',
            name='favorites',
        ),
    ]
